CREATE TABLE AREA_DE_ATENDIMENTO (
  idAREA_DE_ATENDIMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR NULL,
  DESCRICAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idAREA_DE_ATENDIMENTO)
);

CREATE TABLE CONSELHO (
  idCONSELHO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME INTEGER UNSIGNED NULL,
  UF INTEGER UNSIGNED NULL,
  PRIMARY KEY(idCONSELHO)
);

CREATE TABLE CURSO (
  idCURSO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME INTEGER UNSIGNED NULL,
  DURACAO INTEGER UNSIGNED NULL,
  TURNO VARCHAR NULL,
  PRIMARY KEY(idCURSO)
);

CREATE TABLE PESSOA (
  idPESSOA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TIPO INTEGER UNSIGNED NULL,
  NOME INTEGER UNSIGNED NULL,
  CPF INTEGER UNSIGNED NULL,
  RG VARCHAR NULL,
  TELEFONE VARCHAR NULL,
  CELULAR VARCHAR NULL,
  EMAIL VARCHAR NULL,
  CEP INTEGER UNSIGNED NULL,
  UF VARCHAR NULL,
  CIDADE VARCHAR NULL,
  BAIRRO VARCHAR NULL,
  RUA VARCHAR NULL,
  NUMERO INTEGER UNSIGNED NULL,
  COMPLEMENTO VARCHAR NULL,
  SENHA VARCHAR NULL,
  PRIMARY KEY(idPESSOA)
);

CREATE TABLE PACIENTE (
  idPACIENTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOA_idPESSOA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idPACIENTE),
  FOREIGN KEY(PESSOA_idPESSOA)
    REFERENCES PESSOA(idPESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PROFESSOR (
  idPROFESSOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOA_idPESSOA INTEGER UNSIGNED NOT NULL,
  MATRICULA INTEGER UNSIGNED NULL,
  PRIMARY KEY(idPROFESSOR),
  FOREIGN KEY(PESSOA_idPESSOA)
    REFERENCES PESSOA(idPESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DISPONIBILIDADE_PROFESSOR (
  idDISPONIBILIDADE_PROFESSOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  DIA_SEMANA VARCHAR NULL,
  HORARIO TIME NULL,
  PRIMARY KEY(idDISPONIBILIDADE_PROFESSOR),
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ALUNO (
  idALUNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PESSOA_idPESSOA INTEGER UNSIGNED NOT NULL,
  RA INTEGER UNSIGNED NULL,
  PERIODO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idALUNO),
  FOREIGN KEY(PESSOA_idPESSOA)
    REFERENCES PESSOA(idPESSOA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FILIACAO (
  CONSELHO_idCONSELHO INTEGER UNSIGNED NOT NULL,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  DATA_REGISTRO INTEGER UNSIGNED NULL,
  ID_REGISTRO INTEGER UNSIGNED NULL,
  PRIMARY KEY(CONSELHO_idCONSELHO, PROFESSOR_idPROFESSOR),
  FOREIGN KEY(CONSELHO_idCONSELHO)
    REFERENCES CONSELHO(idCONSELHO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DICENCIA (
  CURSO_idCURSO INTEGER UNSIGNED NOT NULL,
  ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(CURSO_idCURSO, ALUNO_idALUNO),
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ALUNO_idALUNO)
    REFERENCES ALUNO(idALUNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DOCENCIA (
  CURSO_idCURSO INTEGER UNSIGNED NOT NULL,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(CURSO_idCURSO, PROFESSOR_idPROFESSOR),
  FOREIGN KEY(CURSO_idCURSO)
    REFERENCES CURSO(idCURSO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AGENDAMENTO (
  idAGENDAMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  PACIENTE_idPACIENTE INTEGER UNSIGNED NOT NULL,
  AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO INTEGER UNSIGNED NOT NULL,
  DATA_SOLICITACAO DATE NULL,
  DATA_CONFIRMACAO DATE NULL,
  CONFIRMACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idAGENDAMENTO),
  FOREIGN KEY(AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO)
    REFERENCES AREA_DE_ATENDIMENTO(idAREA_DE_ATENDIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PACIENTE_idPACIENTE)
    REFERENCES PACIENTE(idPACIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE CONSULTA (
  idCONSULTA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO INTEGER UNSIGNED NOT NULL,
  PACIENTE_idPACIENTE INTEGER UNSIGNED NOT NULL,
  AGENDAMENTO_idAGENDAMENTO INTEGER UNSIGNED NOT NULL,
  DATA_ATENDIMENTO DATE NULL,
  PROCEDIMENTOS VARCHAR NULL,
  RECOMENDACOES INTEGER UNSIGNED NULL,
  CONFIRMACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idCONSULTA),
  FOREIGN KEY(AGENDAMENTO_idAGENDAMENTO)
    REFERENCES AGENDAMENTO(idAGENDAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PACIENTE_idPACIENTE)
    REFERENCES PACIENTE(idPACIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO)
    REFERENCES AREA_DE_ATENDIMENTO(idAREA_DE_ATENDIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE DISPONIBILIDADE_ALUNO (
  idDISPONIBILIDADE_ALUNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  DIA_SEMANA VARCHAR NULL,
  HORARIO TIME NULL,
  PRIMARY KEY(idDISPONIBILIDADE_ALUNO),
  FOREIGN KEY(ALUNO_idALUNO)
    REFERENCES ALUNO(idALUNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FALTA_PROFESSOR_CONSULTA (
  idFALTA_PROFESSOR_CONSULTA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  CONSULTA_idCONSULTA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idFALTA_PROFESSOR_CONSULTA),
  FOREIGN KEY(CONSULTA_idCONSULTA)
    REFERENCES CONSULTA(idCONSULTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ALUNO_has_AGENDAMENTO (
  ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  AGENDAMENTO_idAGENDAMENTO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ALUNO_idALUNO, AGENDAMENTO_idAGENDAMENTO),
  FOREIGN KEY(ALUNO_idALUNO)
    REFERENCES ALUNO(idALUNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AGENDAMENTO_idAGENDAMENTO)
    REFERENCES AGENDAMENTO(idAGENDAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ALUNO_has_CONSULTA (
  ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  CONSULTA_idCONSULTA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ALUNO_idALUNO, CONSULTA_idCONSULTA),
  FOREIGN KEY(ALUNO_idALUNO)
    REFERENCES ALUNO(idALUNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CONSULTA_idCONSULTA)
    REFERENCES CONSULTA(idCONSULTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE RETORNO (
  idRETORNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO INTEGER UNSIGNED NOT NULL,
  PACIENTE_idPACIENTE INTEGER UNSIGNED NOT NULL,
  CONSULTA_idCONSULTA INTEGER UNSIGNED NOT NULL,
  DATA_PREVISTA DATE NULL,
  DATA_ATENDIMENTO DATE NULL,
  RESULTADOS VARCHAR NULL,
  CONFIRMACAO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idRETORNO),
  FOREIGN KEY(CONSULTA_idCONSULTA)
    REFERENCES CONSULTA(idCONSULTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PACIENTE_idPACIENTE)
    REFERENCES PACIENTE(idPACIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AREA_DE_ATENDIMENTO_idAREA_DE_ATENDIMENTO)
    REFERENCES AREA_DE_ATENDIMENTO(idAREA_DE_ATENDIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FALTA_ALUNO (
  idFALTA_ALUNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ALUNO_has_CONSULTA_CONSULTA_idCONSULTA INTEGER UNSIGNED NOT NULL,
  ALUNO_has_CONSULTA_ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idFALTA_ALUNO),
  FOREIGN KEY(ALUNO_has_CONSULTA_ALUNO_idALUNO, ALUNO_has_CONSULTA_CONSULTA_idCONSULTA)
    REFERENCES ALUNO_has_CONSULTA(ALUNO_idALUNO, CONSULTA_idCONSULTA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FALTA_PROFESSOR_RETORNO (
  idFALTA_PROFESSOR_RETORNO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PROFESSOR_idPROFESSOR INTEGER UNSIGNED NOT NULL,
  RETORNO_idRETORNO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idFALTA_PROFESSOR_RETORNO),
  FOREIGN KEY(RETORNO_idRETORNO)
    REFERENCES RETORNO(idRETORNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROFESSOR_idPROFESSOR)
    REFERENCES PROFESSOR(idPROFESSOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ALUNO_has_RETORNO (
  ALUNO_idALUNO INTEGER UNSIGNED NOT NULL,
  RETORNO_idRETORNO INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ALUNO_idALUNO, RETORNO_idRETORNO),
  FOREIGN KEY(ALUNO_idALUNO)
    REFERENCES ALUNO(idALUNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(RETORNO_idRETORNO)
    REFERENCES RETORNO(idRETORNO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);